// Sample.cpp : Defines the entry point for the console application.
//

#include <chrono>
#include <iostream>
#include <tchar.h>

#include "HandleInput.h"
#include "CpuUsage.h"
#include "Razer\ChromaSDKPluginTypes.h"
#include "Razer\ChromaAnimationAPI.h"
#include "RazerKeyboardMapping.h"

using namespace std;
using namespace ChromaSDK;

#pragma region Autogenerated
static void ShowEffect1()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect1");
}
static void ShowEffect2()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect2");
}
static void ShowEffect3()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect3");
}
static void ShowEffect4()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect4");
}
static void ShowEffect5()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect5");
}
static void ShowEffect6()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect6");
}
static void ShowEffect7()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect7");
}
static void ShowEffect8()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect8");
}
static void ShowEffect9()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect9");
}
static void ShowEffect10()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect10");
}
static void ShowEffect11()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect11");
}
static void ShowEffect12()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect12");
}
static void ShowEffect13()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect13");
}
static void ShowEffect14()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect14");
}
static void ShowEffect15()
{
	ChromaAnimationAPI::CoreSetEventName(L"Effect15");
}
#pragma endregion


int _gSelection = 1;
const int MAX_SELECTION = 15;
int _gIndex = 0;
char _gTextBuffer[16];
char _gManualInput[] = {
	' ',
	' ',
};

char _gShortcode[7] = { 0 };
char _gStreamId[48] = { 0 };
char _gStreamKey[48] = { 0 };
unsigned char _gLenShortcode = 0;
unsigned char _gLenStreamId = 0;
unsigned char _gLenStreamKey = 0;

const char* g_FocusGuid = "UnitTest";
char g_Focus[48] = { 0 };
unsigned char g_LenFocus = 0;

static const char* IsSelected()
{
	++_gIndex;
	if (_gIndex == _gSelection)
	{
		return "*";
	}
	else
	{
		if (_gIndex <= 0)
		{
			return " ";
		}
		memset(_gTextBuffer, 0, size(_gTextBuffer));
		sprintf_s(_gTextBuffer, "%d", _gIndex);
		return _gTextBuffer;
	}
}

static void PrintLegend()
{
	for (int i = 0; i < 25; ++i)
	{
		fprintf(stdout, "\r\n");
	}

	fprintf(stdout, "C++ CHROMA GAME SAMPLE APP\r\n");
	fprintf(stdout, "\r\n");

	fprintf(stdout, "Use UP and DOWN arrows to select animation and press ENTER.\r\n");
	fprintf(stdout, "Use ESCAPE to QUIT.\r\n");

	_gIndex = 0;
	for (int effect = 1; effect <= MAX_SELECTION; ++effect)
	{
		fprintf(stdout, "[%s] Effect %d", IsSelected(), effect);
		if (effect % 5 == 0 ||
			effect == MAX_SELECTION)
		{
			fprintf(stdout, "\r\n");
		}
		else
		{
			fprintf(stdout, "\t\t");
		}
	}

	fprintf(stdout, "\r\n");
	fprintf(stdout, "\r\n");
	if (_gSelection > 0)
	{
		fprintf(stdout, "[%d] Press ENTER to play selection. ", _gSelection);
	}
	else
	{
		fprintf(stdout, "[ ] Press ENTER to play selection. ");
	}

	fprintf(stdout, "\r\n");
	if (_gManualInput[0] != ' ')
	{
		fprintf(stdout, "%c", _gManualInput[0]);
		if (_gManualInput[1] != ' ')
		{
			fprintf(stdout, "%c", _gManualInput[1]);
		}
		fprintf(stdout, "\r\n");
	}
}

static void ClearManualInput()
{
	_gManualInput[0] = ' ';
	_gManualInput[1] = ' ';
}

void ExecuteEffect();

static void Cleanup()
{
	if (ChromaAnimationAPI::IsInitialized())
	{
		ChromaAnimationAPI::UseIdleAnimations(false);
		ChromaAnimationAPI::StopAll();
		ChromaAnimationAPI::CloseAll();
		RZRESULT result = ChromaAnimationAPI::Uninit();
		ChromaAnimationAPI::UninitAPI();
		if (result != RZRESULT_SUCCESS)
		{
			cerr << "Failed to uninitialize Chroma! Result=" << result << endl;
			exit(1);
		}
	}
}

int main()
{
	fprintf(stderr, "App launched!\r\n");

	ChromaSDK::APPINFOTYPE appInfo = {};

	wcscpy_s(appInfo.Title, 256, L"Game Sample: Application");
	wcscpy_s(appInfo.Description, 1024, L"A sample application using Razer Chroma SDK");
	wcscpy_s(appInfo.Author.Name, 256, L"Razer");
	wcscpy_s(appInfo.Author.Contact, 256, L"https://wyvrn.com");

	//appInfo.SupportedDevice = 
	//    0x01 | // Keyboards
	//    0x02 | // Mice
	//    0x04 | // Headset
	//    0x08 | // Mousepads
	//    0x10 | // Keypads
	//    0x20   // ChromaLink devices
	appInfo.SupportedDevice = (0x01 | 0x02 | 0x04 | 0x08 | 0x10 | 0x20);
	//    0x01 | // Utility. (To specifiy this is an utility application)
	//    0x02   // Game. (To specifiy this is a game);
	appInfo.Category = 1;

	RZRESULT result = ChromaAnimationAPI::InitSDK(&appInfo);
	if (result != RZRESULT_SUCCESS)
	{
		cerr << "Failed to initialize Chroma!" << endl;
		ChromaAnimationAPI::UninitAPI();
		exit(1);
	}
	Sleep(100); //wait for init

	// Manually set event names
	ChromaAnimationAPI::UseForwardChromaEvents(false);

	// sample for getting the mapping between potential UI key binding enums and RZKEY
	RazerKeyboardMapping* mapping = RazerKeyboardMapping::GetInstance();
	int key = mapping->GetRZKEY(2);

	HandleInput numKeys[] =
	{
		HandleInput('0'),
		HandleInput('1'),
		HandleInput('2'),
		HandleInput('3'),
		HandleInput('4'),
		HandleInput('5'),
		HandleInput('6'),
		HandleInput('7'),
		HandleInput('8'),
		HandleInput('9'),
	};

	HandleInput numpadKeys[] =
	{
		HandleInput(VK_NUMPAD0),
		HandleInput(VK_NUMPAD1),
		HandleInput(VK_NUMPAD2),
		HandleInput(VK_NUMPAD3),
		HandleInput(VK_NUMPAD4),
		HandleInput(VK_NUMPAD5),
		HandleInput(VK_NUMPAD6),
		HandleInput(VK_NUMPAD7),
		HandleInput(VK_NUMPAD8),
		HandleInput(VK_NUMPAD9),
	};

	PrintLegend();
	HandleInput inputUp = HandleInput(VK_UP);
	HandleInput inputDown = HandleInput(VK_DOWN);
	HandleInput inputBackspace = HandleInput(VK_BACK);
	HandleInput inputEnter = HandleInput(VK_RETURN);
	HandleInput inputEscape = HandleInput(VK_ESCAPE);

	int autoPrint = 0;

	while (true)
	{
		if (++autoPrint > 100)
		{
			autoPrint = 0;
			PrintLegend();
		}

		if (inputEscape.WasReleased(true))
		{
			ChromaAnimationAPI::StopAll();
			ChromaAnimationAPI::CloseAll();
			ChromaAnimationAPI::ClearAll();
			ChromaAnimationAPI::Uninit();
			break;
		}
		else if (inputUp.WasReleased(true))
		{
			ClearManualInput();
			if (_gSelection > 1)
			{
				--_gSelection;
			}
			PrintLegend();
			if (_gSelection >= 1)
			{
				ExecuteEffect();
			}
		}


		else if (inputDown.WasReleased(true))
		{
			ClearManualInput();
			if (_gSelection < MAX_SELECTION)
			{
				_gSelection++;
			}
			PrintLegend();
			if (_gSelection > 0)
			{
				ExecuteEffect();
			}
		}

		bool hasManualInput = false;
		if (inputBackspace.WasReleased(true))
		{
			if (_gManualInput[1] != ' ')
			{
				_gManualInput[1] = ' ';
				hasManualInput = true;

			}
			else if (_gManualInput[0] != ' ')
			{
				_gManualInput[0] = ' ';
				hasManualInput = true;
			}
		}
		for (int i = 0; i < (int)size(numKeys); ++i)
		{
			if (numKeys[i].WasReleased(true) ||
				numpadKeys[i].WasReleased(true))
			{
				if (_gManualInput[0] != ' ')
				{
					_gManualInput[1] = numKeys[i].GetKey();
					hasManualInput = true;
				}
				else
				{
					_gManualInput[0] = numKeys[i].GetKey();
					hasManualInput = true;
				}
			}
		}
		if (hasManualInput)
		{
			int val = 0;
			if (_gManualInput[1] != ' ')
			{
				if (_gManualInput[0] >= '0' && _gManualInput[0] <= '9')
				{
					val = 10 * (_gManualInput[0] - '0');
				}
				if (_gManualInput[1] >= '0' && _gManualInput[1] <= '9')
				{
					val += _gManualInput[1] - '0';
				}
			}
			else if (_gManualInput[0] != ' ')
			{
				val = _gManualInput[0] - '0';
			}
			if (val <= MAX_SELECTION)
			{
				_gSelection = val;
			}
			PrintLegend();
		}

		if (inputEnter.WasReleased(true))
		{
			PrintLegend();
			ClearManualInput();

			ExecuteEffect();

			if (_gSelection < 1)
			{
				PrintLegend();
			}
		}
		Sleep(1);
	}

	Cleanup();

	return 0;
}

void ExecuteEffect()
{
	switch (_gSelection)
	{
	case 1:
		ShowEffect1();
		break;
	case 2:
		ShowEffect2();
		break;
	case 3:
		ShowEffect3();
		break;
	case 4:
		ShowEffect4();
		break;
	case 5:
		ShowEffect5();
		break;
	case 6:
		ShowEffect6();
		break;
	case 7:
		ShowEffect7();
		break;
	case 8:
		ShowEffect8();
		break;
	case 9:
		ShowEffect9();
		break;
	case 10:
		ShowEffect10();
		break;
	case 11:
		ShowEffect11();
		break;
	case 12:
		ShowEffect12();
		break;
	case 13:
		ShowEffect13();
		break;
	case 14:
		ShowEffect14();
		break;
	case 15:
		ShowEffect15();
		break;
	}
}
